IDENTIFIER: /[a-zA-Z_][a-zA-Z_0-9]*/

STRING: /"[^"]*"/

OPBIN: /[&|^]/

OPLOG: /\&\&|\|\|/
OPCMP: /<=|>=|==|!=|[<>]/
OPADD: /[+\-]/
OPMUL: /[*\/%]/

PRIMITIVE_TYPE: "int"
    | "double"
    | "str"

COMPOSITE_TYPE: "dict"

?nested_type: PRIMITIVE_TYPE
    | COMPOSITE_TYPE "<" PRIMITIVE_TYPE "," nested_type ">"

decl: nested_type IDENTIFIER

bloc: "{" commande* "}"

parameters: ((decl ",")* decl)?

?expression: log_expr

?log_expr: log_expr OPLOG bit_expr -> binaire
    | bit_expr

?bit_expr: bit_expr OPBIN cmp_expr -> binaire
    | cmp_expr

?cmp_expr: cmp_expr OPCMP add_expr -> binaire
    | add_expr

?add_expr: add_expr OPADD mul_expr -> binaire
    | mul_expr

?mul_expr: mul_expr OPMUL unary -> binaire
    | unary

?unary: "!" unary -> non_logique
    | atom

?atom: IDENTIFIER -> variable
    | SIGNED_INT -> entier
    | SIGNED_FLOAT -> double
    | STRING -> chaine
    | "(" expression ")" -> parenthese
    | dict "[" expression "]" -> dict_access
    | "len" "(" expression ")" -> length
    | "charAt" "(" expression "," expression ")" -> charat
    | "atoi" "(" expression ")" -> atoi
    | PRIMITIVE_TYPE "(" expression ")" -> conversion
    | "{" ((expression ":" expression ",")* expression ":" expression)? "}" -> dict_literal

?dict: IDENTIFIER -> root_dict
    |  dict "[" expression "]" -> dict_access

commande: IDENTIFIER "=" expression ";" -> assignation
    | decl "=" expression ";" -> decl_assignation
    | "pass" -> nop
    | "return" expression ";" -> ret
    | "print" "(" expression ")" ";" -> print
    | "if" "(" expression ")" bloc -> block_if
    | "while" "(" expression ")" bloc -> block_while
    | dict "[" expression "]" "=" expression ";" -> assignation_dict
    | "foreach" "(" IDENTIFIER "in" IDENTIFIER ")" bloc -> foreach
    | "del" IDENTIFIER "[" expression "]" ";" -> del_key

main: "main" "(" parameters ")" bloc

start: main

%import common.WS

%import common.SIGNED_INT

%import common.SIGNED_FLOAT

%ignore WS

%ignore /\/\/[^\n\r]*/

%ignore /\/\*[\s\S]*?\*\//