IDENTIFIER: /[a-zA-Z_][a-zA-Z_0-9]*/

STRING: /"[^"]*"/

OPBIN: /<=|>=|==|!=|[+\-*\/<>%&|^]/

PRIMITIVE_TYPE: "int"
    | "double"
    | "str"

COMPOSITE_TYPE: "dict"

full_type: PRIMITIVE_TYPE
    | COMPOSITE_TYPE "<" PRIMITIVE_TYPE "," full_type ">"

decl: full_type IDENTIFIER

bloc: "{" commande* "}"

parameters: ((decl ",")* decl)?

expression: IDENTIFIER -> variable
    | SIGNED_INT -> entier
    | SIGNED_FLOAT -> double
    | STRING -> chaine
    | "(" expression ")" -> parenthese
    | expression OPBIN expression -> binaire
    | IDENTIFIER "[" expression "]" -> dict_access
    | "len" "(" expression ")" -> length
    | "charAt" "(" expression "," expression ")" -> charat
    | "atoi" "(" expression ")" -> atoi
    | "!" expression -> non_logique
    | PRIMITIVE_TYPE "(" expression ")" -> conversion
    | "{" ((expression ":" expression ",")* expression ":" expression)? "}" -> dict_literal

commande: IDENTIFIER "=" expression ";" -> assignation
    | decl "=" expression ";" -> decl_assignation
    | "pass" -> nop
    | "return" expression ";" -> ret
    | "print" "(" expression ")" ";" -> print
    | "if" "(" expression ")" bloc -> block_if
    | "while" "(" expression ")" bloc -> block_while
    | IDENTIFIER "[" expression "]" "=" expression ";" -> assignation_dict
    | "foreach" "(" IDENTIFIER "in" IDENTIFIER ")" bloc -> foreach

main: "main" "(" parameters ")" bloc

start: main

%import common.WS

%import common.SIGNED_INT

%import common.SIGNED_FLOAT

%ignore WS

%ignore /\/\/[^\n\r]*/

%ignore /\/\*[\s\S]*?\*\//