IDENTIFIER: /[a-zA-Z_][a-zA-Z_0-9]*/

STRING: /"[^"]*"/

CHAR: /'[^']'/

OPBIN: /<=|>=|==|!=|[+\-*\/<>%&|^]/

TYPE.2: "int"
    | "double"
    | "str"

decl: TYPE IDENTIFIER

bloc: "{" commande* "}"

parameters: ((decl ",")* decl)?

expression: IDENTIFIER -> variable
    | SIGNED_INT -> entier
    | SIGNED_FLOAT -> double
    | STRING -> chaine
    | CHAR -> caractere
    | "(" expression ")" -> parenthese
    | expression OPBIN expression -> binaire
    | "len" "(" expression ")" -> length
    | "charAt" "(" expression "," expression ")" -> charat
    | "atoi" "(" expression ")" -> atoi
    | "!" expression -> non_logique
    | TYPE "(" expression ")" -> conversion

commande: IDENTIFIER "=" expression ";" -> assignation
    | decl "=" expression ";" -> decl_assignation
    | "pass" -> nop
    | "return" expression ";" -> ret
    | "print" "(" expression ")" ";" -> print
    | "if" "(" expression ")" bloc -> block_if
    | "while" "(" expression ")" bloc -> block_while

main: "main" "(" parameters ")" bloc

start: main

%import common.WS

%import common.SIGNED_INT

%import common.SIGNED_FLOAT

%ignore WS

%ignore /\/\/[^\n\r]*/

%ignore /\/\*[\s\S]*?\*\//